<dt><strong>v2.9.4</strong> <small>(28/05/2013)</small></dt>
<dd>
	<p><span class="bug">bug</span>Correction d'un bug de variable d'environnement</p>
</dd>

<dt><strong>v2.9.3</strong> <small>(06/02/2013)</small></dt>
<dd>
	<p><span class="code">code</span>Ajout de l'IP hôte dans la modal "À propos de..."</p>
</dd>

<dt><strong>v2.9.2</strong> <small>(29/01/2013)</small></dt>
<dd>
	<p><span class="bug">bug</span>Protection des caractères spéciaux dans les titres</p>
</dd>

<dt><strong>v2.9.1</strong> <small>(23/01/2013)</small></dt>
<dd>
	<p><span class="code">code</span>Affinage du nettoyage des RichBrick</p>
</dd>

<dt><strong>v2.9</strong> <small>(22/01/2013)</small></dt>
<dd>
	<p><span class="code">code</span>Refactor de la procédure d'envoi de mail des FormBrick</p>
</dd>

<dt><strong>v2.8.11</strong> <small>(22/01/2013)</small></dt>
<dd>
	<p><span class="code">code</span>Traduction du message de feedback d'envoi de formulaire</p>
</dd>

<dt><strong>v2.8.10</strong> <small>(22/01/2013)</small></dt>
<dd>
	<p><span class="code">code</span>Prise en charge des éventuels &lt;div&gt; perdus dans les RichBrick</p>
</dd>

<dt><strong>v2.8.9</strong> <small>(18/01/2013)</small></dt>
<dd>
	<p><span class="bug">bug</span>Bugfix sur le label des FileBrick</p>
	<p><span class="code">code</span>Ajout du système de restauration dans les Brick File</p>
</dd>

<dt><strong>v2.8.8.1</strong> <small>(18/01/2013)</small></dt>
<dd>
	<p><span class="code">code</span>Merge</p>
</dd>

<dt><strong>v2.8.8</strong> <small>(18/01/2013)</small></dt>
<dd>
	<p><span class="bug">bug</span>Bugfix sur les brick form et file dans le mode multilangue</p>
</dd>

<dt><strong>v2.8.7</strong> <small>(17/01/2013)</small></dt>
<dd>
	<p><span class="bug">bug</span>Bugfix sur la vérification du sitemap</p>
</dd>

<dt><strong>v2.8.6</strong> <small>(17/01/2013)</small></dt>
<dd>
	<p><span class="bug">bug</span>Bugfix sur la construction du sitemap</p>
</dd>

<dt><strong>v2.8.5</strong> <small>(17/01/2013)</small></dt>
<dd>
	<p><span class="bug">bug</span>Bugfix sur l'upload d'images</p>
</dd>

<dt><strong>v2.8.4</strong> <small>(13/01/2013)</small></dt>
<dd>
	<p><span class="bug">bug</span>Bugfix sur le routage des langues</p>
</dd>

<dt><strong>v2.8.3</strong> <small>(27/12/2012)</small></dt>
<dd>
	<p><span class="new">new</span>Dynamic sitemap generation.</p>
</dd>

<dt><strong>v2.8.2</strong> <small>(27/12/2012)</small></dt>
<dd>
	<p><span class="bug">bug</span>Correction d'un bug sur le routage.</p>
	<p><span class="new">new</span>Prise en charge d'un attribute data-preserve-link sur les liens.</p>
</dd>

<dt><strong>v2.8.1</strong> <small>(27/12/2012)</small></dt>
<dd>
	<p><span class="code">code</span>Mise à jour de jQuery en 1.8.3.</p>
</dd>

<dt><strong>v2.8</strong> <small>(24/12/2012)</small></dt>
<dd>
	<p><span class="new">new</span>Briques conditionnelles en fonction de la langue.</p>
</dd>

<dt><strong>v2.7.1</strong> <small>(11/12/2012)</small></dt>
<dd>
	<p><span class="code">code</span>Affinage de la génération du robots.txt (SEO)</p>
</dd>

<dt><strong>v2.7</strong> <small>(11/12/2012)</small></dt>
<dd>
	<p><span class="new">new</span>Ajout des FileBrick, support des balises &lt;a&gt;</p>
</dd>

<dt><strong>v2.6</strong> <small>(9/12/2012)</small></dt>
<dd>
	<p><span class="code">code</span>Refactor complet de tous le code javascript</p>
</dd>

<dt><strong>v2.5.2</strong> <small>(18/10/2012)</small></dt>
<dd>
	<p><span class="code">code</span>Ajout d'une route spécifique pour les fichiers de verif SEO Google</p>
</dd>

<dt><strong>v2.5.1</strong> <small>(18/10/2012)</small></dt>
<dd>
	<p><span class="code">code</span>Mise à jour de jQuery UI en v1.9.0</p>
</dd>

<dt><strong>v2.5</strong> <small>(05/10/2012)</small></dt>
<dd>
	<p><span class="new">new</span>Ajout des TimeBrick, support des balises &lt;time&gt;.</p>
</dd>

<dt><strong>v2.4.3</strong> <small>(30/09/2012)</small></dt>
<dd>
	<p><span class="dgn">design</span>Amélioration du feedback visuel des brick list</p>
	<p><span class="bug">bug</span>Correction d'un bug dans l'affichage du feedback des brick list pour les sous-brick Rich</p>
</dd>

<dt><strong>v2.4.2</strong> <small>(27/09/2012)</small></dt>
<dd>
	<p><span class="new">new</span>Tooltip différent pour les zones faisant partie d'une liste</p>
</dd>

<dt><strong>v2.4.1</strong> <small>(04/09/2012)</small></dt>
<dd>
	<p><span class="new">new</span>Ajout du changelog dans la Modal "à propos de…"</p>
</dd>

<dt><strong>v2.4</strong> <small>(04/09/2012)</small></dt>
<dd>
	<p><span class="code">code</span>Prise en charge des balises table en ListBricks</p>
</dd>

<dt><strong>v2.3.7</strong> <small>(29/08/2012)</small></dt>
<dd>
	<p><span class="bug">bug</span>Correction d'un bug d'encodage d'entités sur le render public des RichBricks</p>
</dd>

<dt><strong>v2.3.6</strong> <small>(29/08/2012)</small></dt>
<dd>
	<p><span class="bug">bug</span>Correction d'un bug de parsage de l'adresse de référence pour les FormBricks</p>
	<p><span class="bug">bug</span>Correction d'un bug d'encodage d'entités sur les RichBricks</p>
	<p><span class="code">code</span>Mise à jour de jQuery en v1.8.0</p>
</dd>

<dt><strong>v2.3.5</strong> <small>(26/08/2012)</small></dt>
<dd>
	<p><span class="bug">bug</span>Correction d'un bug de références sur les FormBricks</p>
</dd>

<dt><strong>v2.3.4</strong> <small>(18/08/2012)</small></dt>
<dd>
	<p><span class="bug">bug</span>Correction d'un bug dans le render des ListBricks</p>
</dd>

<dt><strong>v2.3.3</strong> <small>(16/08/2012)</small></dt>
<dd>
	<p><span class="bug">bug</span>Correction d'une erreur d'interprétation des esperluettes dans les Bricks de texte</p>
</dd>

<dt><strong>v2.3.2</strong> <small>(16/08/2012)</small></dt>
<dd>
	<p><span class="bug">bug</span>Correction d'un bug javascript sur la gestion du sitemap</p>
</dd>

<dt><strong>v2.3.1</strong> <small>(16/08/2012)</small></dt>
<dd>
	<p><span class="code">code</span>Ajout d'une classe "active" sur l'élément courrant dans les MenuBricks</p>
	<p><span class="code">code</span>Déplacement de l'affectation de la classe posib-editable dans Brick</p>
	<p><span class="code">code</span>Modification de la méthode utilitaire de chargement des classes pour ajouter un paramètre d'ordre de chargements</p>
	<p><span class="bug">bug</span>Correction du DOMParser::getNodeContent</p>
	<p><span class="bug">bug</span>Correction d'un bug sur l'initialisation des RichBricks</p>
	<p><span class="dgn">design</span>Mise à jour du reset</p>
</dd>

<dt><strong>v2.3</strong> <small>(6/08/2012)</small></dt>
<dd>
	<p><span class="code">code</span>Refactor RichBricks, changement de la balise de base pour les RichBricks</p>
</dd>

<dt><strong>v2.2.1</strong> <small>(6/08/2012)</small></dt>
<dd>
	<p><span class="new">new</span>Embryon de Modal "À propos de…"</p>
	<p><span class="dgn">design</span>Application d'un reset sur les tooltips</p>
</dd>

<dt><strong>v2.2</strong> <small>(6/08/2012)</small></dt>
<dd>
	<p><span class="new">new</span>Ajout des ListBricks, mode Liste</p>
</dd>

<dt><strong>v2.1</strong> <small>(25/07/2012)</small></dt>
<dd>
	<p><span class="new">new</span>mode Multilangues</p>
</dd>

<dt><strong>v2.0.4</strong> <small>(27/06/2012)</small></dt>
<dd>
	<p><span class="code">code</span>Mise à jour de la lib wout en 1.α.3</p>
</dd>

<dt><strong>v2.0.3</strong> <small>(27/06/2012)</small></dt>
<dd>
	<p><span class="bug">bug</span>Correction de bugs divers dans la gestion du multipage</p>
</dd>

<dt><strong>v2.0.2</strong> <small>(26/06/2012)</small></dt>
<dd>
	<p><span class="bug">bug</span>Bugfix</p>
</dd>

<dt><strong>v2.0.1</strong> <small>(26/06/2012)</small></dt>
<dd>
	<p><span class="new">new</span>Version 2, refonte complète du système</p>
</dd>
