<div id="posib-ie-warning" class="posib-reset">
	<div>
		<h4>Attention ! </h4>
		<p>Si ce message ne disparaît pas, votre navigateur présente de sérieuses lacunes en terme de sécurité et de performances, dues à son obsolescence.</p>
		<p>En conséquence, l'outil d'administration de votre site sera inutilisable.</p>
		<p>Veuillez installer un navigateur récent (<a href="http://www.google.com/chrome?hl=fr">Chrome</a>, <a href="http://www.mozilla-europe.org/fr/firefox/">Firefox</a>, <a href="http://www.apple.com/fr/safari/download/">Safari</a>), ou le mettre à jour si vous utilisez déjà l'un des navigateurs cités, pour continuer.</p>
	</div>
</div>
