<input type="hidden" name="ref" value="<?=$brick->ref ?>" />
<input type="hidden" name="page" value="<?=$brick->page ?>" />

<div class="posib-field-group">
	<label for="posib-short-content">
		Votre contenu :
	</label>
	<div class="posib-input">
		<input type="text" class="posib-xlarge" name="content" id="posib-short-content" value="<?=$brick->content; ?>" autofocus="autofocus" autocomplete="off" />
	</div>
</div>
